### ISSUE TITLE
[Bug/Feature] NBT only with CTRL changes

### ISSUE THREAD

**Issue by StarsDown64** [zabi94/NBTTooltip#10]
The config option for NBT only with CTRL doesn't work as I believe it should by its description.
When I have it on, the NBT data will still display when I'm not holding anything. It displays underneath the other parts of the item description. The only thing pressing CTRL does is maximize the NBT data, getting rid of the other text of the item.
Video demonstration attached: [https://imgur.com/a/Lyh7jO7](https://imgur.com/a/Lyh7jO7)
If this is how it's intended, I think the description should be changed.

Note: I tried this with the Require F3 + H enabled option on and off, but it had no effect on the issue.

**Comment by zabi94** [comment]
When I wrote the description I meant 
`Show (nbt only) when pressing ctrl`
And not
`Show nbt (only when pressing ctrl)`
I guess I'll rephrase the description to make it clearer

**Comment by StarsDown64** [comment]
Fair enough, but I highly recommend adding the other feature as well. Many of my friends would like to use the mod, but keep it disabled because there's no toggle. There are times when it's useful to see nbt but it's infrequent. Closing our games and reloading to enable the mod is a hassle. So, please consider adding this as a feature.

**Comment by StarsDown64** [comment]
Also for the rephrase, I recommend the word "just" instead of "only".

**Comment by zabi94** [comment]
As for the toggle, disabling advanced tooltips (f3+h while no GUI is open) is the way to remove the nbt data display. 

I discourage using this in actual gameplays, as it should never be necessary, this was meant as a mod/modpack developer tool.

I recommend asking the mod developer of whatever mod you need nbt info from to actually add the data to the item description instead, as it may be useful to other people too.

**Comment by StarsDown64** [comment]
For each of your comments:
1) I use F3+H regularly (always) during normal gameplay.
2) I am using it as a developer tool, I'm an operator on the server and it's necessary sometimes
3) I'm using it for vanilla items or to verify custom items aren't forged
Despite your suggestions, I still think you should add a toggle. It's commonplace to have the option to disable a mod in game. Just saying.

**Comment by zabi94** [comment]
Fair
