### ISSUE TITLE
AttributeModifiers error

### ISSUE THREAD

**Issue by suzakuwcx** [zabi94/NBTTooltip#11]
[![64MuNQ.png](https://z3.ax1x.com/2021/03/20/64MuNQ.png)](https://imgtu.com/i/64MuNQ)
this is a part of respond
```
  {
    "Amount": 8.0,
    "Slot": "chest",
    "AttributeName": "minecraft:generic.armor",
    "Operation": ,
    "UUID": [
      5648299,
      17825335,
      -15753219,
      4619561
    ],
    "Name": "generic.armor"
  },
```
but  after checking in the '/give' command the correct is 
```
  {
    "Amount": 8.0,
    "Slot": "chest",
    "AttributeName": "minecraft:generic.armor",
    "Operation": 1,
    "UUID": [I;
      5648299,
      17825335,
      -15753219,
      4619561
    ],
    "Name": "generic.armor"
  },
```

**Comment by zabi94** [comment]
Are you sure there is the `I;` part after UUID?  
The missing 1 is effectively a bug

**Comment by suzakuwcx** [comment]
yeah , without the` "I;"` ,the attribute will disapper in new item

**Comment by zabi94** [comment]
With that the output is no longer a valid json

**Comment by suzakuwcx** [comment]
```/give @s diamond_axe{AttributeModifiers:[{Slot:"mainhand",AttributeName:"generic.attack_damage",Name:"generic.attack_damage",Amount:20,Operation:0,UUID:[I;1498693494,1027158888,1898994005,860320107]}]}```
this is an example copy from wiki ,without `I;` the attribute will lost

**Comment by zabi94** [comment]
Well, yeah, because that functionality is not supposed to give you something valid for the /give command, it's supposed to be in JSON format

**Comment by suzakuwcx** [comment]
understand, Thank you!

**Comment by zabi94** [comment]
I'll have a internal NBT format renderer next version for that

**Comment by zabi94** [comment]
version 1.1.2 should be soon available on curseforge and modrinth, fixes the missing this digit bug and adds a way to copy NBT to use on the `/give` command
