### ISSUE TITLE
Large tooltip view improvements

### ISSUE THREAD

**Issue by Felix14-v2** [zabi94/NBTTooltip#13]
Currently, auto scrolling is used to view long tooltips. This is not very convenient. Is it possible to intercept cursor movement to convert it to tooltips scrolling (with Show_on_key trigger type)?

**Comment by zabi94** [comment]
I might look into a better way to support scrolling the tooltip in the future, but I'm not really sure how. 

- Using keybinds seems overkill and unintuitive
- mouse wheel is already used by other mods to move items between inventories
- mouse movements would make it really difficult to control
