### ISSUE TITLE
Minor issues in 1.2.0

### ISSUE THREAD

**Issue by Felix14-v2** [zabi94/NBTTooltip#17]
Thank you so much for mod updating! So, here are some minor issues in the new features:
• Unusual control keys like side mouse keys (Button 4, Button 5...) or amesc keys do not work for scroll control. I hope it is possible to fix.
• nbt scrolling not stops after pressing the scroll key (partially fixed by setting a huge scrolling delay)
• carriage return symbol in the end of copied text (useful for json but inconvenient for "mc give nbt")
[[Short demo](https://youtu.be/CZgrOjSGfSg)]

**Comment by zabi94** [comment]
Sorry for the long delay in my response, I was pretty busy and I couldn't get to it

> Unusual control keys like side mouse keys (Button 4, Button 5...) or amesc keys do not work for scroll control. I hope it is possible to fix.  

I'm sure there's a way to fix those, but I don't have such a mouse so I can't really fix it. If you could be so kind to tell me what system you have (OS + mouse model) I can check if I can borrow something similar from friends.

> nbt scrolling not stops after pressing the scroll key (partially fixed by setting a huge scrolling delay)  

It actually stops for a few seconds, the intended way for it to work is to press the button that stops the scrolling. I'll check if there's a way to make it feel better without rewriting half of the mod's code

> carriage return symbol in the end of copied text (useful for json but inconvenient for "mc give nbt")  

I'll fix that in a sec

**Comment by zabi94** [comment]
Scrolling now stops when pressing up/down with commit e593caa

**Comment by zabi94** [comment]
I'm not actually able to reproduce the CR at the end of the copied tooltip. It never shows up for me. Would you mind sharing your mod list?

**Comment by Felix14-v2** [comment]
Oh, it was caused by a Color Uchained mod (removes the restriction on entering technical characters like § into the chat). I forget about it (◔◡◔)

**Comment by Felix14-v2** [comment]
> If you could be so kind to tell me what system you have (OS + mouse model) I can check if I can borrow something similar from friends

I'm sorry, I don't know how I could have missed this... Windows 10 Home, OKLICK 745 G
