### ISSUE TITLE
[Suggestion] Manual scroll toggle

### ISSUE THREAD

**Issue by HexedHero** [zabi94/NBTTooltip#26]
Add a toggle to switch between an auto scroller and a manual scroll using two keybinds such as W and S to scroll up and down.

**Comment by zabi94** [comment]
The feature is already available in the mod

**Comment by HexedHero** [comment]
It still auto scrolls while you try and manually scroll yourself, fighting you.

**Comment by zabi94** [comment]
There should be a keybind to stop it. Hold it while using up and down
