### ISSUE TITLE
[Request] Forge source

### ISSUE THREAD

**Issue by Jacrispys** [zabi94/NBTTooltip#28]
Any chance I could get the source for 1.12 on forge? I wanted to make a 1.8.9 port for personal use, but its difficult since decompiled source is obfuscated by forge.

**Comment by zabi94** [comment]
1.12 source code is already available in the master branch of this repo

**Comment by Jacrispys** [comment]
Ah perfect! I only saw Fabric branches at first look derp. This should be pretty straight forward after I figure out how 1.8 forge config works.
