### ISSUE TITLE
1.12.2 "supposed" nbt tooltip was said to have tile editor 

### ISSUE THREAD

**Issue by supreme1233** [zabi94/NBTTooltip#31]
i tried doing it but for some reason it didnt work it said on the curseforge page that older versions would work and 1.12.2 is the oldest version i couldve find i want to find tiles nbt for a project and it has to be on 1.18.1 so what i am thinking of is somehow trueporting it to 1.18.1 but i would only do that if i can see the nbt which i am currently not able to

**Comment by supreme1233** [comment]
and also what sort of custom settings are you talking about in the curseforge pls tell me

**Comment by supreme1233** [comment]
discord link? for further progress on it?

**Comment by zabi94** [comment]
I can't understand a single thing from the original question, it's missing all punctuation and I'm not losing my morning decyphering the thing, sorry.

[Discord server](https://discord.gg/7PxyW7yS)

Why was this closed so quickly?
