### ISSUE TITLE
Update to Minecraft 1.19

### ISSUE THREAD

**Issue by Felix14-v2** [zabi94/NBTTooltip#32]
Absolutely no pressure, but it would be great to have such a useful tool in the latest MC version 🙂
NBT Tooltip just crashes when opening inventory now.
[latest.log](https://github.com/zabi94/NBTTooltip/files/8936348/latest.log)

**Comment by zabi94** [comment]
The current version does not support 1.19, a crash is what I expected.

My current pc is broken, I'm waiting for the last components to be shipped to build the new one and finally be able to update this. I hope to have a new version going by the end of next weekend.

**Comment by zabi94** [comment]
updated sooner than anticipated
