### ISSUE TITLE
Ignore Empty NBT

### ISSUE THREAD

**Issue by ghost** [zabi94/NBTTooltip#34]
If the item has no NBT, simply don't display any extra text at all.

Seeing this is not useful whatsoever:

![image](https://user-images.githubusercontent.com/24266948/180932816-adceb75c-a68c-44b4-b65e-418d31376826.png)

**Comment by zabi94** [comment]
Weird, I could have sworn this was already in the mod. I'll fix for next release

**Comment by ghost** [comment]
I should have provided some version info too:
`MC 1.18.2`
`Fabric Loader 0.14.8`
`Fabric API 0.58.0+1.18.2`
`NBTToolTip 1.6.0`
