### ISSUE TITLE
Tooltip not showing up

### ISSUE THREAD

**Issue by Chilllyy** [zabi94/NBTTooltip#37]
When hovering over items, the nbt doesn't show up, using the toggle keybind doesn't fix this either.

**To Reproduce**
4. See bug

1. Hover over items
2. No NBT Showing

**Expected behavior**
The NBT Shows Up

**Screenshots**
![image](https://user-images.githubusercontent.com/117584956/205426840-b217cef6-f5df-4380-9f83-d871256fd1bf.png)

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - latest.log: 
[latest.log](https://github.com/zabi94/NBTTooltip/files/10145783/latest.log)

 - Modpack link (preferred) or Mod List:
 NBTToolTip
 - Custom changes to modpack (if using a modpack):
 - NBTTooltips Config:
[nbttooltip.txt](https://github.com/zabi94/NBTTooltip/files/10145785/nbttooltip.txt)
(It was a json, couldn't upload to github)

**Environment (please complete the following information):**
 - Mod Version: 1.7.0
 - MC Version: 1.19.2
 - Fabric Version: 0.14.10 1.19.2
 - Fabric API version: Fabric API 0.62.0 1.19.2
 - System: Windows 10
 - Installation type: Server

**Additional context**
I've uninstalled all my other mods as well as turning my packs off, and it changed nothing

**Comment by zabi94** [comment]
In your configuration change the trigger type from F3H to toggle_on_key
