### ISSUE TITLE
Configuration to change item used to view block nbt?

### ISSUE THREAD

**Issue by boot2big** [zabi94/NBTTooltip#4]
Maybe I'd like to use glowstone, or a sword, instead of an arrow.
So perhaps a config option to set this? (With the option of, by default, minecraft:arrow)

**Comment by zabi94** [comment]
What's the problem with the arrow? It's not meant to be used in survival, so it's not really an issue

**Comment by boot2big** [comment]
Well the issue is that this _can_ be used in survival.
Lets say I might have an unobtainable item, such as a creative battery from a tech mod.
Maybe I would be able to set it to that?

**Comment by zabi94** [comment]
But why would you?
