### ISSUE TITLE
Update to 1.19.4 pls

### ISSUE THREAD

**Issue by Cyclopropinon** [zabi94/NBTTooltip#42]

**Comment by NyaomiDEV** [comment]
It works on 1.19.4. Do not trust Modrinth! (though, a dependency update might be good to have regardless)

**Comment by Cyclopropinon** [comment]
ah ok.
btw can u also write on modrinth, for wich snapshots this works?

**Comment by zabi94** [comment]
I'd rather not have people try use my mods on snapshots.
I added compatibility with 1.19.4 both on modrinth and curseforge
