### ISSUE TITLE
1.20.4 Crash while copying

### ISSUE THREAD

**Issue by SheerYin** [zabi94/NBTTooltip#48]
**Describe the bug**
Crash when copying using ->

**To Reproduce**
Crash when copying using ->

**Expected behavior**

**Screenshots**

**Pastebin links**
https://pastebin.com/ZwCuMw5t

**Environment (please complete the following information):**
 - Mod Version: 1.20.4
 - MC Version: 1.20.4
 - Fabric Version: Fabric Loader 0.15.6
 - Fabric API version: fabric-api 0.95.1+1.20.4
 - System: Windows 10
 - Installation type: SinglePlayer

**Additional context**
Even if only fabric-api-0.95.1+1.20.4.jar + nbttooltip-1.7.2.jar crashes when copied

**Comment by zabi94** [comment]
The mod hasn't been updated to work with 1.20.4 yet, the last verified minecraft version is 1.20.2 I think

**Comment by SheerYin** [comment]
ok
