### ISSUE TITLE
Wider Lore Boxes

### ISSUE THREAD

**Issue by ItsMias** [zabi94/NBTTooltip#51]
I work a lot with items with gradients in them, I would love to see an option to make the box wider or to remove certain things from showing up, see the image below, by just making the box bigger it could already get a lot more clear to read!
![image](https://github.com/zabi94/NBTTooltip/assets/126190882/8f4f7389-1f27-4225-9df4-8fc0d6a3b2d2)

**Comment by zabi94** [comment]
This is beyond the scope of this mod, check projects like https://www.curseforge.com/minecraft/mc-mods/adaptive-tooltips to change a tooltip's appearance
