### ISSUE TITLE
Game crashes when opening inventory

### ISSUE THREAD

**Issue by ninjaguardian** [zabi94/NBTTooltip#53]
#### Please install [Not Enough Crashes](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes) to allow me to read the stack trace

**To Reproduce**
Steps to reproduce the crash:
1. Open your inventory

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - Crash Log: https://mclo.gs/Y9fAvTf
 - NBTTooltip Config: https://pastebin.com/SsBQKFBJ

**Environment (please complete the following information):**
 - Mod Version: [e.g. 1.2.0] 1.8.1
 - MC Version: [e.g. 1.16.1] 1.21
 - Fabric Version: [e.g. 0.6.1.45] 0.16.0
 - Fabric API version: [e.g. Fabric API 0.16.2 build 385] 0.100.8+1.21
 - System: [e.g. Windows 10, Mac OS Big Sur, Manjaro Linux]  Windows 11
 - Installation type: [e.g. SinglePlayer, DedicatedServer, Lan] Client (singleplayer)

**Additional context**
Add any other context about the problem here, like other mods that you think might be involved in the problem.

**Comment by zabi94** [comment]
The mod is not compatible with 1.21 yet
