### ISSUE TITLE
License ambiguity between Github and CurseForge

### ISSUE THREAD

**Issue by ericsgardner** [zabi94/NBTTooltip#6]
Here on Github, the project appears to be using [the MIT license](https://github.com/zabi94/NBTTooltip/blob/master/LICENSE). However, on CurseForge the license is [All Rights Reserved](https://www.curseforge.com/project/274816/license). I am assuming that the project is actually MIT licensed, and the CurseForge info is just an oversight, given that you have chosen to host the source code on Github. I would just like to confirm my assumption. Thank you!

**Comment by zabi94** [comment]
Yup, fixed on CF
