### ISSUE TITLE
Not compatible with mod "Advanced NBT Tooltip"

### ISSUE THREAD

**Issue by TheMuffinPony** [zabi94/NBTTooltip#8]
See issue b0iizz/minecraft-advancednbttooltip#19 for full description.
# Summary of issue
A similar mod, Advanced NBT Tooltip, will overwrite NBT Tooltip's tooltip when both are installed simultaneously.

**Comment by b0iizz** [comment]
This was actually an issue with my mod. This is hopefully fixed in the next version of my mod (1.3.1)!
